name: nlp-base-env
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex
  - asttokens
  - backcall
  - blas
  - bottleneck
  - brotlipy
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - cryptography
  - cudatoolkit
  - debugpy
  - decorator
  - entrypoints
  - et_xmlfile
  - executing
  - ffmpeg
  - fftw
  - freetype
  - giflib
  - gmp
  - gnutls
  - idna
  - intel-openmp
  - ipykernel
  - ipython
  - jedi
  - joblib
  - jpeg
  - jupyter_client
  - jupyter_core
  - lame
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libdeflate
  - libffi
  - libgfortran-ng
  - libgfortran5
  - libidn2
  - libopus
  - libpng
  - libsodium
  - libtasn1
  - libtiff
  - libunistring
  - libvpx
  - libwebp
  - libwebp-base
  - lz4-c
  - matplotlib-inline
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses
  - nest-asyncio
  - nettle
  - numexpr
  - numpy
  - numpy-base
  - openh264
  - openpyxl
  - openssl
  - packaging
  - pandas
  - parso
  - pexpect
  - pickleshare
  - pillow
  - pip
  - prompt-toolkit
  - psutil
  - ptyprocess
  - pure_eval
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pysocks
  - python
  - python-dateutil
  - pytorch
  - pytorch-mutex
  - pytz
  - pyzmq
  - readline
  - requests
  - scikit-learn
  - scipy
  - setuptools
  - six
  - sqlite
  - stack_data
  - threadpoolctl
  - tk
  - torchaudio
  - torchvision
  - tornado
  - traitlets
  - typing_extensions
  - urllib3
  - wcwidth
  - wheel
  - x264
  - xz
  - zeromq
  - zlib
  - zstd
  - pip:
    - absl-py
    - accelerate
    - aiohttp
    - aiosignal
    - astunparse
    - async-generator
    - async-timeout
    - attrs
    - beautifulsoup4
    - bs4
    - cachetools
    - click
    - cvxpy
    - cycler
    - datasets
    - dill
    - ecos
    - emoji
    - exceptiongroup
    - fastjsonschema
    - filelock
    - flatbuffers
    - fonttools
    - frozenlist
    - fsspec
    - gast
    - google-auth
    - google-auth-oauthlib
    - google-pasta
    - grpcio
    - h11
    - h5py
    - huggingface-hub
    - importlib-metadata
    - importlib-resources
    - jsonschema
    - keras
    - kiwisolver
    - libclang
    - markdown
    - markupsafe
    - matplotlib
    - multidict
    - multiprocess
    - nbformat
    - nltk
    - oauthlib
    - openai
    - opt-einsum
    - osqp
    - outcome
    - patsy
    - pkgutil-resolve-name
    - plotly
    - protobuf
    - pyarrow
    - pyasn1
    - pyasn1-modules
    - pyrsistent
    - python-dotenv
    - pyyaml
    - qdldl
    - regex
    - requests-oauthlib
    - responses
    - rsa
    - scs
    - selenium
    - sniffio
    - sortedcontainers
    - soupsieve
    - statsmodels
    - tenacity
    - tensorboard
    - tensorboard-data-server
    - tensorboard-plugin-wit
    - tensorflow
    - tensorflow-estimator
    - tensorflow-io-gcs-filesystem
    - termcolor
    - tokenizers
    - tqdm
    - transformers
    - trio
    - trio-websocket
    - webdriver-manager
    - werkzeug
    - wrapt
    - wsproto
    - xxhash
    - yarl
    - zipp
